version: '3'

services:
  database:
    container_name: mysql-database
    image: mysql:8.0.31
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cashforce_v3
      - MYSQL_ROOT_PASSWORD=123456
