version: '3'

services:
  database:
    container_name: mysql-database
    image: mysql:8.0.31
    volumes:
      - ./sql-dump:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cashforce_v3
      - MYSQL_ROOT_PASSWORD=123456
  backend:
    build: ./backend
    image: node-api
    restart: always
    ports:
      - "5050:5050"
      - "9222:9222"
    environment:
      - MYSQL_DBHOST=database
    depends_on:
      - database
  frontend:
    build: ./frontend
    image: vue-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend